services:
  postgresql:
    image: docker.io/bitnami/postgresql:16
    restart: unless-stopped
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=keycloak
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - 'postgresql_data:/bitnami/postgresql'

  keycloak:
    image: docker.io/bitnami/keycloak:24.0.2
    container_name: keycloak
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_EXTRA_ARGS: --import-realm
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    volumes:
      - ./docker/realms:/opt/bitnami/keycloak/data/import
volumes:
  postgresql_data:
    driver: local
