spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            authorization-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
            jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
        registration:
          google:
            client-id: google-client-id
            client-secret: //google client secret
            authorization-grant-type: authorization_code

          keycloak:
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
            client-name: ${keycloak.client-id}
            redirect-uri: http://localhost:8888/*
            authorization-grant-type: authorization_code

  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  file:
    upload-dir: ./uploads/files
server:
  port: 8888
logging:
  level:
    root: info
    web: info
  file:
    path: ./log/application
  logback:
    rolling policy:
      max-file-size: 10MB
keycloak:
  realm: planning
  client-id: theara
  server-url: http://localhost:8080
  client-secret: oBiM0TtZTUpyOnBUKyvpF4K8FWyY8Iig
  token-url: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
  auth-url: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
springdoc:
  swagger-ui:
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}
      realm: ${keycloak.realm}

