spring:
  datasource:
    url: jdbc:mysql://localhost:3344/pos?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: "***Theara2384056***"
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
app:
  file:
    upload-dir: ./uploads/files
server:
  port: 8888
logging:
  level:
    com.example.mysmallproject: DEBUG
    org.hibernate: ERROR
  file:
    path: ./log/application.log
  logback:
    rolling policy:
      max-file-size: 1MB
